export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
/// to add product ///

export const ADD_PRODUCT = "ADD_PRODUCT";
